DROP TABLE IF EXISTS launchers;
DROP TABLE IF EXISTS repos;

CREATE TABLE launchers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE repos (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255)
);
